package api

import (
	"log/slog"
	"strconv"
	"time"

	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/cors"
	"github.com/gofiber/fiber/v3/middleware/recover"
	"gorm.io/gorm"

	_ "github.com/awang-karisma/trustpilot-scraper/docs" // docs is generated by Swag CLI
	swagger "github.com/gofiber/contrib/v3/swaggo"

	"github.com/awang-karisma/trustpilot-scraper/internal/api/handlers"
	"github.com/awang-karisma/trustpilot-scraper/internal/config"
	"github.com/awang-karisma/trustpilot-scraper/internal/scheduler"
	"github.com/awang-karisma/trustpilot-scraper/internal/webhook"
)

// Server represents the API server
type Server struct {
	app       *fiber.App
	config    *config.ServiceConfig
	db        *gorm.DB
	scheduler *scheduler.Scheduler
	logger    *slog.Logger
}

// NewServer creates a new API server
func NewServer(cfg *config.ServiceConfig, db *gorm.DB, sched *scheduler.Scheduler, logger *slog.Logger) *Server {
	app := fiber.New(fiber.Config{
		AppName: "Trustpilot Scraper API v1.0",
	})

	// Middleware
	app.Use(recover.New())
	app.Use(cors.New(cors.Config{
		AllowOrigins: []string{"*"},
		AllowMethods: []string{"GET", "POST", "PUT", "DELETE"},
		AllowHeaders: []string{"Content-Type", "Authorization"},
	}))

	// Swagger documentation
	app.Use("/swagger/*", swagger.HandlerDefault)

	s := &Server{
		app:       app,
		config:    cfg,
		db:        db,
		scheduler: sched,
		logger:    logger,
	}

	s.registerRoutes()
	return s
}

// registerRoutes registers all API routes
func (s *Server) registerRoutes() {
	// Health check
	s.app.Get("/health", func(c fiber.Ctx) error {
		return c.JSON(fiber.Map{
			"status":    "ok",
			"timestamp": time.Now(),
			"version":   "1.0.0",
		})
	})

	// API routes
	api := s.app.Group("/api")

	// Create webhook service
	var webhookService *webhook.WebhookService
	if s.config.WebhookURL != "" {
		webhookService = webhook.NewWebhookService(s.config.WebhookURL, s.config.WebhookTemplate)
	}

	// Website routes
	websiteHandler := handlers.NewWebsiteHandler(s.db, s.scheduler)
	api.Get("/websites", websiteHandler.List)
	api.Post("/websites", websiteHandler.Create)
	api.Get("/websites/:id", websiteHandler.Get)
	api.Put("/websites/:id", websiteHandler.Update)
	api.Delete("/websites/:id", websiteHandler.Delete)
	api.Post("/websites/:id/scrape", websiteHandler.TriggerScrape)

	// Review routes
	reviewHandler := handlers.NewReviewHandler(s.db)
	api.Get("/reviews", reviewHandler.List)
	api.Get("/reviews/:id", reviewHandler.Get)
	api.Get("/websites/:id/reviews", reviewHandler.ListByWebsite)

	// Rating routes
	ratingHandler := handlers.NewRatingHandler(s.db)
	api.Get("/websites/:id/ratings", ratingHandler.GetHistory)

	// Webhook routes
	webhookHandler := handlers.NewWebhookHandler(s.db, webhookService)
	api.Post("/websites/:id/webhook", webhookHandler.Trigger)
	api.Post("/webhook/test", webhookHandler.Test)

	// Job routes
	jobHandler := handlers.NewJobHandler(s.db)
	api.Get("/jobs", jobHandler.List)
	api.Get("/jobs/:id", jobHandler.Get)

	// Stats
	statsHandler := handlers.NewStatsHandler(s.db)
	api.Get("/stats", statsHandler.Get)
}

// Start starts the API server
func (s *Server) Start() error {
	addr := s.config.APIHost + ":" + strconv.Itoa(s.config.APIPort)
	s.logger.Info("Starting API server", "addr", addr)
	return s.app.Listen(addr)
}

// Shutdown gracefully shuts down the server
func (s *Server) Shutdown() error {
	s.logger.Info("Shutting down API server")
	return s.app.Shutdown()
}

// App returns the underlying Fiber app
func (s *Server) App() *fiber.App {
	return s.app
}
