// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/jobs": {
            "get": {
                "description": "Get jobs with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "List jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status (pending, running, completed, failed)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by website ID",
                        "name": "website_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.JobListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/jobs/{id}": {
            "get": {
                "description": "Get a job by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get a job",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.JobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/notifications": {
            "get": {
                "description": "Get a list of all notification channels",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "List notification channels",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Filter by enabled status",
                        "name": "enabled",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by website ID",
                        "name": "website_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.NotificationListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Register a new notification channel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Create a new notification channel",
                "parameters": [
                    {
                        "description": "Notification channel details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.CreateNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.NotificationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/notifications/{id}": {
            "get": {
                "description": "Get a notification channel by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Get a notification channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notification Channel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.NotificationResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update notification channel details by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Update a notification channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notification Channel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Notification channel details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.UpdateNotificationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.NotificationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a notification channel by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Delete a notification channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notification Channel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/notifications/{id}/jobs": {
            "get": {
                "description": "Get notification jobs for a specific channel",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "List notification jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notification Channel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (pending, sent, failed)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.NotificationJobListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/notifications/{id}/trigger": {
            "post": {
                "description": "Manually trigger an immediate notification for a channel",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "notifications"
                ],
                "summary": "Trigger a notification",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notification Channel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/reviews": {
            "get": {
                "description": "Get paginated reviews with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "List reviews",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by website ID",
                        "name": "website_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by rating (comma-separated, e.g., 1,2,3)",
                        "name": "rating",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "date desc",
                        "description": "Sort order (e.g., date desc, rating asc)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search in title and content",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ReviewListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/reviews/{id}": {
            "get": {
                "description": "Get a review by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "Get a review",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Review ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/stats": {
            "get": {
                "description": "Get overall service statistics including websites, reviews, jobs, and queue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get service statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.StatsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/templates": {
            "get": {
                "description": "Get a list of all notification templates",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "List all templates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.TemplateListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Register a new notification template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Create a new template",
                "parameters": [
                    {
                        "description": "Template details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.CreateTemplateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.TemplateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/templates/{id}": {
            "get": {
                "description": "Get a notification template by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Get a template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.TemplateResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update notification template details by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Update a template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Template details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.UpdateTemplateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.TemplateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a notification template by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Delete a template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/templates/{id}/validate": {
            "post": {
                "description": "Check if a template file exists and is valid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "templates"
                ],
                "summary": "Validate a template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/websites": {
            "get": {
                "description": "Get a list of all registered websites to scrape",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websites"
                ],
                "summary": "List all websites",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.WebsiteListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Register a new website for scraping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websites"
                ],
                "summary": "Create a new website",
                "parameters": [
                    {
                        "description": "Website details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.CreateWebsiteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.WebsiteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/websites/{id}": {
            "get": {
                "description": "Get a registered website by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websites"
                ],
                "summary": "Get a website",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Website ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.WebsiteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update registered website details by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websites"
                ],
                "summary": "Update a website",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Website ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Website details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.UpdateWebsiteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.WebsiteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a registered website by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websites"
                ],
                "summary": "Delete a website",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Website ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/websites/{id}/ratings": {
            "get": {
                "description": "Get rating history for a website",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ratings"
                ],
                "summary": "Get rating history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Website ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 30,
                        "description": "Number of records",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.RatingHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/websites/{id}/reviews": {
            "get": {
                "description": "Get paginated reviews for a specific website",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reviews"
                ],
                "summary": "List reviews by website",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Website ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by rating (comma-separated)",
                        "name": "rating",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "date desc",
                        "description": "Sort order",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ReviewListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/websites/{id}/scrape": {
            "post": {
                "description": "Manually trigger an immediate scraping job for a website",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websites"
                ],
                "summary": "Trigger a scrape",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Website ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.CreateNotificationRequest": {
            "type": "object",
            "required": [
                "name",
                "schedule",
                "template_id",
                "webhook_url",
                "website_id"
            ],
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                },
                "template_id": {
                    "type": "string"
                },
                "webhook_url": {
                    "type": "string"
                },
                "website_id": {
                    "type": "string"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.CreateTemplateRequest": {
            "type": "object",
            "required": [
                "file_name",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "file_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.CreateWebsiteRequest": {
            "type": "object",
            "required": [
                "base_url",
                "name"
            ],
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "max_pages": {
                    "type": "integer",
                    "maximum": 50,
                    "minimum": 1
                },
                "name": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.JobListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.JobResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.JobResponse": {
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "reviews_found": {
                    "type": "integer"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "website_id": {
                    "type": "integer"
                },
                "website_name": {
                    "type": "string"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.JobStats": {
            "type": "object",
            "properties": {
                "completed_today": {
                    "type": "integer"
                },
                "failed_today": {
                    "type": "integer"
                },
                "pending": {
                    "type": "integer"
                },
                "running": {
                    "type": "integer"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.NotificationJobListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.NotificationJobResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.NotificationJobResponse": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "sent_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.NotificationListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.NotificationResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.NotificationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                },
                "template_id": {
                    "type": "string"
                },
                "template_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "webhook_url": {
                    "type": "string"
                },
                "website_id": {
                    "type": "string"
                },
                "website_name": {
                    "type": "string"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.QueueStats": {
            "type": "object",
            "properties": {
                "size": {
                    "type": "integer"
                },
                "workers_active": {
                    "type": "integer"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.RatingHistoryResponse": {
            "type": "object",
            "properties": {
                "current": {
                    "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.RatingSnapshot"
                },
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.RatingSnapshot"
                    }
                },
                "website_id": {
                    "type": "integer"
                },
                "website_name": {
                    "type": "string"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.RatingSnapshot": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ReviewListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ReviewResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.Pagination"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ReviewResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "rating": {
                    "type": "integer"
                },
                "review_id": {
                    "type": "string"
                },
                "reviewer": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "website_id": {
                    "type": "integer"
                },
                "website_name": {
                    "type": "string"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ReviewStats": {
            "type": "object",
            "properties": {
                "bad_reviews": {
                    "description": "1-2 star reviews",
                    "type": "integer"
                },
                "this_week": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.StatsResponse": {
            "type": "object",
            "properties": {
                "jobs": {
                    "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.JobStats"
                },
                "queue": {
                    "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.QueueStats"
                },
                "reviews": {
                    "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.ReviewStats"
                },
                "websites": {
                    "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.WebsiteStats"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.TemplateListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.TemplateResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.TemplateResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "file_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.UpdateNotificationRequest": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                },
                "schedule": {
                    "type": "string"
                },
                "template_id": {
                    "type": "string",
                    "minLength": 1
                },
                "webhook_url": {
                    "type": "string"
                },
                "website_id": {
                    "type": "string"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.UpdateTemplateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "file_name": {
                    "type": "string",
                    "minLength": 1
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.UpdateWebsiteRequest": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "max_pages": {
                    "type": "integer",
                    "maximum": 50,
                    "minimum": 1
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                },
                "schedule": {
                    "type": "string"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.WebsiteListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_awang-karisma_trustpilot-scraper_internal_api_dto.WebsiteResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.WebsiteResponse": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "last_scraped": {
                    "type": "string"
                },
                "max_pages": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_awang-karisma_trustpilot-scraper_internal_api_dto.WebsiteStats": {
            "type": "object",
            "properties": {
                "disabled": {
                    "type": "integer"
                },
                "enabled": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Trustpilot Scraper API",
	Description:      "This is a Trustpilot Scraper API server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
